version: '3.8'

services:

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./uploads:/uploads
      - ./resized:/resized
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A src.domain.celery.worker worker --loglevel=info
    volumes:
      - ./uploads:/uploads
      - ./resized:/resized
    env_file: .env
    depends_on:
      - web
      - redis


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
